name: nlp20230531
channels:
  - microsoft
  - pytorch
  - huggingface
  - main
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - aiohttp=3.8.3=py310h5eee18b_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - alsa-lib=1.2.8=h166bdaf_0
  - anytree=2.8.0=pyh9f0ad1d_0
  - appdirs=1.4.4=pyhd3eb1b0_0
  - arrow=1.2.3=py310h06a4308_1
  - arrow-cpp=10.0.1=h3e2b116_4_cpu
  - astroid=2.14.2=py310h06a4308_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - async-timeout=4.0.2=py310h06a4308_0
  - attr=2.5.1=h166bdaf_1
  - attrs=22.1.0=py310h06a4308_0
  - aws-c-auth=0.6.21=hd93a3ba_3
  - aws-c-cal=0.5.20=hd3b2fe5_3
  - aws-c-common=0.8.5=h166bdaf_0
  - aws-c-compression=0.2.16=hf5f93bc_0
  - aws-c-event-stream=0.2.17=h57874a7_1
  - aws-c-http=0.7.0=h96ef541_0
  - aws-c-io=0.13.12=h57ca295_1
  - aws-c-mqtt=0.7.13=h0b5698f_12
  - aws-c-s3=0.2.1=h5d7e488_4
  - aws-c-sdkutils=0.1.7=hf5f93bc_0
  - aws-checksums=0.1.14=h6027aba_0
  - aws-crt-cpp=0.18.16=h26430d7_8
  - aws-sdk-cpp=1.9.379=h56135f1_7
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.12.2=py310h06a4308_0
  - binaryornot=0.4.4=pyhd3eb1b0_1
  - blas=1.0=mkl
  - boost-cpp=1.81.0=he95ae9e_0
  - bottleneck=1.3.5=py310ha9d4c09_0
  - brotli=1.0.9=h5eee18b_7
  - brotli-bin=1.0.9=h5eee18b_7
  - brotlipy=0.7.0=py310h7f8727e_1002
  - bs4=4.12.2=py38hd3eb1b0_0
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.19.0=h5eee18b_0
  - ca-certificates=2023.01.10=h06a4308_0
  - catalogue=2.0.7=py310h06a4308_0
  - cattrs=23.1.1=pyhd8ed1ab_0
  - certifi=2022.12.7=py310h06a4308_0
  - cffi=1.15.1=py310h5eee18b_3
  - chardet=4.0.0=py310h06a4308_1003
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.0.4=py310h06a4308_0
  - colorama=0.4.6=py310h06a4308_0
  - comm=0.1.2=py310h06a4308_0
  - confection=0.0.4=py310hfdc917e_1
  - contourpy=1.0.5=py310hdb19cb5_0
  - cookiecutter=1.7.3=pyhd3eb1b0_0
  - cryptography=39.0.1=py310h9ce1e76_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - cupy=12.0.0=py310h9216885_1
  - cycler=0.11.0=pyhd3eb1b0_0
  - cymem=2.0.6=py310h295c915_0
  - cython-blis=0.7.9=py310hde88566_1
  - dataclasses=0.8=pyh6d0b6a4_7
  - dataclasses-json=0.5.7=pyhd8ed1ab_0
  - datasets=2.12.0=py_0
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.5.1=py310h295c915_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - dill=0.3.6=py310h06a4308_0
  - evaluate=0.4.0=py310h06a4308_0
  - exceptiongroup=1.0.4=py310h06a4308_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.5.0=hcb278e6_1
  - exrex=0.10.5=py_0
  - fastrlock=0.8=py310hd8f1fbe_3
  - ffmpeg=4.3=hf484d3e_0
  - fftw=3.3.10=nompi_hf0379b8_106
  - filelock=3.9.0=py310h06a4308_0
  - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
  - font-ttf-inconsolata=2.001=hcb22688_0
  - font-ttf-source-code-pro=2.030=hd3eb1b0_0
  - font-ttf-ubuntu=0.83=h8b1ccd4_0
  - fontconfig=2.14.1=h4c34cd2_2
  - fonts-anaconda=1=h8fa9717_0
  - fonts-conda-ecosystem=1=hd3eb1b0_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.12.1=h4a9f257_0
  - frozenlist=1.3.3=py310h5eee18b_0
  - fsspec=2023.4.0=py310h06a4308_0
  - gettext=0.21.1=h27087fc_0
  - gflags=2.2.2=he6710b0_0
  - giflib=5.2.1=h5eee18b_3
  - glib=2.76.3=hfc55251_0
  - glib-tools=2.76.3=hfc55251_0
  - glog=0.6.0=h6f12383_0
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - greenlet=2.0.1=py310h6a678d5_0
  - gst-plugins-base=1.21.3=h4243ec0_1
  - gstreamer=1.21.3=h25f0c4b_1
  - gstreamer-orc=0.4.34=hd590300_0
  - huggingface_hub=0.14.1=py_0
  - icu=70.1=h27087fc_0
  - idna=3.4=py310h06a4308_0
  - importlib-metadata=6.0.0=py310h06a4308_0
  - importlib_metadata=6.0.0=hd3eb1b0_0
  - inflect=6.0.4=pyhd8ed1ab_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - ipykernel=6.19.2=py310h2f386ee_0
  - ipython=8.12.0=py310h06a4308_0
  - ipywidgets=8.0.4=py310h06a4308_0
  - isort=5.9.3=pyhd3eb1b0_0
  - itsdangerous=2.0.1=pyhd3eb1b0_0
  - jack=1.9.22=h11f4161_0
  - jedi=0.18.1=py310h06a4308_1
  - jinja2=3.1.2=py310h06a4308_0
  - jinja2-time=0.2.0=pyhd3eb1b0_3
  - joblib=1.1.1=py310h06a4308_0
  - jpeg=9e=h5eee18b_1
  - jupyter_client=8.1.0=py310h06a4308_0
  - jupyter_core=5.3.0=py310h06a4308_0
  - jupyterlab_widgets=3.0.5=py310h06a4308_0
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.4=py310h6a678d5_0
  - krb5=1.20.1=hf9c8cef_0
  - lame=3.100=h7b6447c_0
  - langcodes=3.3.0=pyhd3eb1b0_0
  - langdetect=1.0.9=pyhd8ed1ab_0
  - lazy-object-proxy=1.6.0=py310h7f8727e_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libabseil=20220623.0=cxx17_h05df665_6
  - libarrow=10.0.1=hee49ebd_4_cpu
  - libbrotlicommon=1.0.9=h5eee18b_7
  - libbrotlidec=1.0.9=h5eee18b_7
  - libbrotlienc=1.0.9=h5eee18b_7
  - libcap=2.66=ha37c62d_0
  - libclang=15.0.7=default_h7634d5b_2
  - libclang13=15.0.7=default_h9986a30_2
  - libcrc32c=1.1.2=h6a678d5_0
  - libcups=2.3.3=h36d4200_3
  - libcurl=7.87.0=h6312ad2_0
  - libdb=6.2.32=h6a678d5_1
  - libdeflate=1.17=h5eee18b_0
  - libedit=3.1.20221030=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.10=h9b69904_4
  - libexpat=2.5.0=hcb278e6_1
  - libffi=3.4.2=h6a678d5_6
  - libflac=1.4.2=h27087fc_0
  - libgcc-ng=12.2.0=h65d4601_19
  - libgcrypt=1.10.1=h166bdaf_0
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libglib=2.76.3=hebfc3b9_0
  - libgomp=12.2.0=h65d4601_19
  - libgoogle-cloud=2.5.0=h5d50b59_1
  - libgpg-error=1.46=h620e276_0
  - libgrpc=1.51.1=h05bd8bd_0
  - libiconv=1.17=h166bdaf_0
  - libidn2=2.3.2=h7f8727e_0
  - libllvm15=15.0.7=hadd5161_1
  - libnghttp2=1.51.0=hdcd2b5c_0
  - libogg=1.3.5=h27cfd23_1
  - libopus=1.3.1=h7b6447c_0
  - libpng=1.6.39=h5eee18b_0
  - libpq=15.1=h2baec63_3
  - libprotobuf=3.21.12=h3eb15da_0
  - libsentencepiece=0.1.97=h43f1d4c_0
  - libsndfile=1.2.0=hb75c966_0
  - libsodium=1.0.18=h7b6447c_0
  - libsqlite=3.42.0=h2797004_0
  - libssh2=1.10.0=h8f2d780_0
  - libstdcxx-ng=12.2.0=h46fd767_19
  - libsystemd0=252=h2a991cd_0
  - libtasn1=4.19.0=h5eee18b_0
  - libthrift=0.16.0=h491838f_2
  - libtiff=4.5.0=h6a678d5_2
  - libtool=2.4.7=h27087fc_0
  - libudev1=253=h0b41bf4_0
  - libunistring=0.9.10=h27cfd23_0
  - libutf8proc=2.8.0=h166bdaf_0
  - libuuid=1.41.5=h5eee18b_0
  - libvorbis=1.3.7=h7b6447c_0
  - libwebp=1.2.4=h11a3e52_1
  - libwebp-base=1.2.4=h5eee18b_1
  - libxcb=1.13=h1bed415_1
  - libxkbcommon=1.5.0=h79f4944_1
  - libxml2=2.10.3=hca2bb57_4
  - libxslt=1.1.37=h873f0b0_0
  - libzlib=1.2.13=h166bdaf_4
  - lxml=4.9.2=py310h5eee18b_0
  - lz4-c=1.9.4=h6a678d5_0
  - markupsafe=2.1.1=py310h7f8727e_0
  - marshmallow=3.19.0=pyhd8ed1ab_0
  - marshmallow-enum=1.5.1=py310h06a4308_0
  - matplotlib=3.7.1=py310h06a4308_1
  - matplotlib-base=3.7.1=py310h1128e8f_1
  - matplotlib-inline=0.1.6=py310h06a4308_0
  - mccabe=0.7.0=pyhd3eb1b0_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py310h7f8727e_0
  - mkl_fft=1.3.1=py310hd6ae3a3_0
  - mkl_random=1.2.2=py310h00e6091_0
  - mpg123=1.31.3=hcb278e6_0
  - multidict=6.0.2=py310h5eee18b_0
  - multiprocess=0.70.14=py310h06a4308_0
  - munkres=1.1.4=py_0
  - murmurhash=1.0.7=py310h295c915_0
  - mypy_extensions=0.4.3=py310h06a4308_0
  - mysql-common=8.0.32=h14678bc_0
  - mysql-libs=8.0.32=h54cf53e_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.5.6=py310h06a4308_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.1=pyhd8ed1ab_0
  - nltk=3.7=pyhd3eb1b0_0
  - nspr=4.35=h27087fc_0
  - nss=3.89=he45b914_0
  - numexpr=2.8.4=py310h8879344_0
  - numpy=1.24.3=py310hd5efca6_0
  - numpy-base=1.24.3=py310h8e6c178_0
  - openh264=2.1.1=h4ff587b_0
  - openssl=1.1.1t=h7f8727e_0
  - orc=1.8.2=hfdbbad2_2
  - packaging=23.0=py310h06a4308_0
  - pandas=1.5.3=py310h1128e8f_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pathy=0.10.1=py310h06a4308_0
  - pcre2=10.40=hc3806b6_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.4.0=py310h6a678d5_0
  - pip=23.0.1=py310h06a4308_0
  - platformdirs=2.5.2=py310h06a4308_0
  - playwright=v1.32.1=py310_0
  - ply=3.11=py310h06a4308_0
  - pooch=1.4.0=pyhd3eb1b0_0
  - poyo=0.5.0=pyhd3eb1b0_0
  - preshed=3.0.6=py310h295c915_0
  - prompt-toolkit=3.0.36=py310h06a4308_0
  - protobuf=4.21.12=py310heca2aa9_0
  - psutil=5.9.0=py310h5eee18b_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pulseaudio=16.1=h4ab2085_1
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pyarrow=10.0.1=py310h468efa6_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pydantic=1.10.2=py310h5eee18b_0
  - pyee=9.0.4=py310h06a4308_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - pylint=2.16.2=py310h06a4308_0
  - pyopenssl=23.0.0=py310h06a4308_0
  - pyparsing=3.0.9=py310h06a4308_0
  - pyqt=5.15.7=py310hab646b1_3
  - pyqt5-sip=12.11.0=py310heca2aa9_3
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.11=h7a1cb2a_2
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-slugify=5.0.2=pyhd3eb1b0_0
  - python-xxhash=2.0.2=py310h5eee18b_1
  - python_abi=3.10=2_cp310
  - pytorch=1.12.1=py3.10_cuda11.3_cudnn8.3.2_0
  - pytorch-mutex=1.0=cuda
  - pytz=2022.7=py310h06a4308_0
  - pyyaml=6.0=py310h5eee18b_1
  - pyzmq=25.0.2=py310h6a678d5_0
  - qt-main=5.15.6=h62441b5_5
  - rapidfuzz=3.0.0=py310heca2aa9_0
  - re2=2022.06.01=h27087fc_1
  - readline=8.2=h5eee18b_0
  - regex=2022.7.9=py310h5eee18b_0
  - requests=2.29.0=py310h06a4308_0
  - requests-cache=1.0.1=pyhd8ed1ab_0
  - requests-file=1.5.1=pyhd3eb1b0_0
  - requests-toolbelt=0.9.1=pyhd3eb1b0_0
  - responses=0.13.3=pyhd3eb1b0_0
  - s2n=1.3.31=hae46d1a_0
  - sacremoses=master=py_0
  - scikit-learn=1.2.1=py310h6a678d5_0
  - scipy=1.10.1=py310hd5efca6_0
  - seaborn=0.12.2=py310h06a4308_0
  - sentence-transformers=2.2.2=pyhd8ed1ab_0
  - sentencepiece=0.1.97=hff52083_0
  - sentencepiece-python=0.1.97=py310h385333e_0
  - sentencepiece-spm=0.1.97=h43f1d4c_0
  - setuptools=66.0.0=py310h06a4308_0
  - shellingham=1.5.0=py310h06a4308_0
  - sip=6.7.9=py310hc6cd4ac_0
  - six=1.16.0=pyhd3eb1b0_1
  - smart_open=5.2.1=py310h06a4308_0
  - snappy=1.1.9=h295c915_0
  - soupsieve=2.4=py310h06a4308_0
  - spacy=3.5.3=py310hfb6f7a9_0
  - spacy-alignments=0.9.0=py310hbdeaff8_0
  - spacy-legacy=3.0.12=pyhd8ed1ab_0
  - spacy-loggers=1.0.1=pyhd3eb1b0_0
  - spacy-model-en_core_web_lg=3.5.0=pyhd8ed1ab_0
  - spacy-model-en_core_web_md=3.5.0=pyhd8ed1ab_0
  - spacy-model-en_core_web_sm=3.5.0=pyhd8ed1ab_0
  - spacy-model-en_core_web_trf=3.5.0=pyh55bf090_0
  - spacy-transformers=1.2.4=py310hfb6f7a9_0
  - sqlite=3.41.2=h5eee18b_0
  - srsly=2.4.6=py310h6a678d5_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - stringcase=1.2.0=py_0
  - text-unidecode=1.3=pyhd3eb1b0_0
  - thinc=8.1.10=py310hfb6f7a9_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tk=8.6.12=h1ccaba5_0
  - tldextract=3.4.4=pyhd8ed1ab_0
  - tokenizers=0.11.4=py310h3dcd8bd_1
  - toml=0.10.2=pyhd3eb1b0_0
  - tomli=2.0.1=py310h06a4308_0
  - tomlkit=0.11.1=py310h06a4308_0
  - torchvision=0.13.1=py310_cu113
  - tornado=6.2=py310h5eee18b_0
  - tqdm=4.65.0=py310h2f386ee_0
  - traitlets=5.7.1=py310h06a4308_0
  - transformers=4.28.1=py_0
  - typer=0.4.1=py310h06a4308_0
  - typing-extensions=4.5.0=py310h06a4308_0
  - typing_extensions=4.5.0=py310h06a4308_0
  - typing_inspect=0.7.1=pyhd3eb1b0_0
  - tzdata=2023c=h04d1e81_0
  - ujson=5.4.0=py310h6a678d5_0
  - unidecode=1.3.6=pyhd8ed1ab_0
  - url-normalize=1.4.3=pyhd8ed1ab_0
  - urllib3=1.26.15=py310h06a4308_0
  - wasabi=0.9.1=py310h06a4308_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - werkzeug=2.2.3=py310h06a4308_0
  - wheel=0.38.4=py310h06a4308_0
  - widgetsnbextension=4.0.5=py310h06a4308_0
  - wrapt=1.14.1=py310h5eee18b_0
  - xcb-util=0.4.0=h516909a_0
  - xcb-util-image=0.4.0=h166bdaf_0
  - xcb-util-keysyms=0.4.0=h516909a_0
  - xcb-util-renderutil=0.3.9=h166bdaf_0
  - xcb-util-wm=0.4.1=h516909a_0
  - xkeyboard-config=2.38=h0b41bf4_0
  - xxhash=0.8.0=h7f8727e_3
  - xz=5.2.10=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - yarl=1.8.1=py310h5eee18b_0
  - zeromq=4.3.4=h2531618_0
  - zipp=3.11.0=py310h06a4308_0
  - zlib=1.2.13=h166bdaf_4
  - zstd=1.5.5=hc292b87_0
  - pip:
      - doccano-client==1.2.7
      - setfit==0.7.0
